project:
  type: default

title: "Modelagem e Otimização de Sistemas Térmicos"

format:
  html:
    # output-file: será dado no comando de linha
    execute:
      echo: false
  pdf:
    # output-file: será dado no comando de linha
    execute:
      echo: false
  revealjs:
    theme: default
    slide-number: true
    # output-file: será dado no comando de linha
    center: false
    scrollable: true
    margin: 0.05
    width: 1366
    height: 768
    css: assets/slides.css     # caminho do slides.css
    code-overflow: wrap
    execute:
      echo: false
